[package]
name = "ya-runtime-vm"
version = "0.1.0"
authors = ["Golem"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

