[package]
name = "ya-runtime-vm"
version = "0.1.0"
authors = ["Golem Factory <contact@golem.network>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
anyhow = "1.0"
bollard-stubs = "1.40.2"
env_logger = "0.7.1"
futures = "0.3"
log = "0.4.8"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
strip-ansi-escapes = "0.1.0"
structopt = "0.3"
tokio = { version = "0.2", features = ["fs", "io-std", "io-util", "macros", "process", "rt-core", "rt-threaded", "sync", "time", "uds"] }
uuid = { version = "0.8", features = ["v4"] }
ya-runtime-api = { version = "0.1", features = ["codec"] }

[dev-dependencies]
tempdir = "0.3.7"

[lib]
name = "ya_runtime_vm"
path = "src/lib.rs"

[[bin]]
name = "ya-runtime-vm"
path = "src/main.rs"
